export const SemesterOptions = [
    { value: 1, label: "Topic 1", key: "1" },
    { value: 2, label: "Topic 2", key: "2" },
    { value: 3, label: "Topic 3", key: "3" },
    { value: 4, label: "Topic 4", key: "4" },
    { value: 5, label: "Topic 5", key: "5" },
];

export const Columns = [
    { id: "id", label: "ID", width: "3%", align: "center", style: { left: "13px" } },
    { id: "topic", label: "Topic", width: "10%", align: "left" },
    { id: "year", label: "Year", width: "3%", align: "center", style: { left: "13px" } },
    { id: "semester", label: "Semester", width: "15%", align: "left" },
    { id: "department", label: "Department", width: "15%", align: "left" },
    { id: "startDate", label: "Start Date", width: "10%", align: "left" },
    { id: "closureDate", label: "Closure Date", width: "10%", align: "left" },
    { id: "finalDate", label: "Final Date", width: "13%", align: "left" },
];

export const Data = [
    {
        id: 1,
        topic: "Halloween 1",
        year: "2022",
        semester: "Semester Winter Year 2022",
        department: "Technology Department",
        startDate: "01/01/2022",
        closureDate: "09/30/2022",
        finalDate: "10/15/2022",
    },
    {
        id: 2,
        topic: "Halloween 2",
        year: "2022",
        semester: "Semester Winter Year 2022",
        department: "Human Resources Department",
        startDate: "01/01/2022",
        closureDate: "09/30/2022",
        finalDate: "10/15/2022",
    },
    {
        id: 3,
        topic: "Halloween 3",
        year: "2023",
        semester: "Semester Winter Year 2023",
        department: "Technology Department",
        startDate: "01/01/2023",
        closureDate: "09/30/2023",
        finalDate: "10/15/2023",
    },
    {
        id: 4,
        topic: "Halloween 4",
        year: "2023",
        semester: "Semester Winter Year 2023",
        department: "Human Resources Department",
        startDate: "01/01/2023",
        closureDate: "09/30/2023",
        finalDate: "10/15/2023",
    },
    {
        id: 5,
        topic: "Halloween 5",
        year: "2023",
        semester: "Semester Winter Year 2023",
        department: "Economics Department",
        startDate: "01/01/2023",
        closureDate: "09/30/2023",
        finalDate: "10/15/2023",
    },
    {
        id: 6,
        topic: "Halloween 6",
        year: "2024",
        semester: "Semester Winter Year 2024",
        department: "Technology Department",
        startDate: "01/01/2024",
        closureDate: "09/30/2024",
        finalDate: "10/15/2024",
    },
    {
        id: 7,
        topic: "Halloween 7",
        year: "2024",
        semester: "Semester Winter Year 2024",
        department: "Human Resources Department",
        startDate: "01/01/2024",
        closureDate: "09/30/2024",
        finalDate: "10/15/2024",
    },
    {
        id: 8,
        topic: "Halloween 8",
        year: "2024",
        semester: "Semester Winter Year 2024",
        department: "Economics Department",
        startDate: "01/01/2024",
        closureDate: "09/30/2024",
        finalDate: "10/15/2024",
    },
]